# Generated by Django 2.2.1 on 2019-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('group_id', models.CharField(default=None, max_length=100)),
                ('payer_id', models.CharField(default=None, max_length=100)),
                ('amount', models.IntegerField(default=0, max_length=20)),
                ('payment_id', models.CharField(default=None, max_length=20)),
                ('description', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default=None, max_length=100)),
                ('creditor_id', models.CharField(default=None, max_length=100)),
                ('debtor_id', models.CharField(default=None, max_length=100)),
                ('amount', models.IntegerField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=None, max_length=20)),
                ('user_id', models.CharField(default=None, max_length=100)),
                ('share', models.FloatField(default=0.0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default=None, max_length=100)),
                ('last_command', models.IntegerField(default=0)),
                ('command_state', models.IntegerField(default=0)),
            ],
        ),
    ]
