# Generated by Django 2.2.1 on 2019-06-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default=None, max_length=100)),
                ('var_name', models.CharField(default=None, max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('group_id', models.CharField(default=None, max_length=100)),
                ('payer_id', models.CharField(default=None, max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('payment_id', models.CharField(default=None, max_length=20)),
                ('description', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default=None, max_length=100)),
                ('user_id', models.CharField(default=None, max_length=100)),
                ('last_command', models.IntegerField(default=0)),
                ('command_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Shares',
            new_name='Share',
        ),
        migrations.DeleteModel(
            name='Costs',
        ),
        migrations.DeleteModel(
            name='States',
        ),
        migrations.AlterField(
            model_name='owe',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
