# Generated by Django 2.2.1 on 2019-06-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20190606_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='user_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
