# Generated by Django 2.2.1 on 2019-06-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='share',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='share',
            name='cost',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.Cost'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
